safe:			false
source:			.
destination:	_gh-pages
lsi:			false
markdown:		rdiscount
pygments:		true
permalink:		pretty
baseurl: 		"http://eadpucv.github.io/pix"
exclude:		[bower_components, src]
project:		PiX
name: "Type Icons"