safe:			false
source:			.
destination:	_gh-pages
lsi:			false
markdown:		rdiscount
highlighter:	true
permalink:		pretty
baseurl: 		"http://eadpucv.github.io/pix"
exclude:		[bower_components, src]
name: 			"PiX"
pixver:			"4.0"